extends RefCounted

const RogueDropCatalog = preload("res://src/adventure/rogue_drop_catalog.gd")

const TEST_CONFIG_PATH := "user://silent_rogue_drop_pool.json"

class DropLevel:
	extends RefCounted
	var map_x := 7
	var map_y := 7
	var block: Array = []
	var obstacle_instances: Dictionary = {}
	var item_instances: Dictionary = {}
	var headless_visuals := true

	func should_load_visuals() -> bool:
		return not headless_visuals

	func _init() -> void:
		for _layer in range(2):
			var columns: Array = []
			for _x in range(map_x):
				var column: Array = []
				column.resize(map_y)
				column.fill(0)
				columns.append(column)
			block.append(columns)

func run() -> Array[String]:
	var failures: Array[String] = []
	var original_level = Game.current_level
	var config := {
		"chance": 1.0,
		"entries": [{"item_id": "bomb_up", "rarity": "uncommon", "weight": 1.0}],
	}
	_write_config(config)
	var loaded := RogueDropCatalog.load_config(TEST_CONFIG_PATH)
	if loaded != config:
		failures.append("editable Rogue drop configuration did not round-trip")
	_write_config({
		"chance": 1.0,
		"entries": [{"item_id": "missing_item", "rarity": "rare", "weight": 1.0}],
	})
	if not RogueDropCatalog.load_config(TEST_CONFIG_PATH).is_empty():
		failures.append("drop catalog accepted an item id that does not exist")
	_write_config(config)

	var level := DropLevel.new()
	Game.current_level = level
	var hero := Hero.new("Asha", Vector2i(3, 3), C.CHARACTER_RED, false)
	hero.bomb = 1
	hero.remain_bombs = 1
	hero.power = 1
	hero.base_speed = 1.0
	hero.speed = 1.0
	var original_bomb := hero.bomb
	var npc := Npc.new("YeWaiFireBall", Vector2i(3, 3), C.CHARACTER_RED, false)
	npc.blood = 1500
	npc.npc_file_name = "YeWaiFireBall"
	npc.rogue_drop_config_path = TEST_CONFIG_PATH
	npc.drop_rng = RandomNumberGenerator.new()
	npc.drop_rng.seed = 20260915
	npc.die()

	var upgrade = _find_item(level.item_instances, "bomb_up")
	if upgrade == null:
		failures.append("NPC death did not create the configured Rogue pickup")
	else:
		upgrade.player_get(hero)
		if hero.bomb != original_bomb + 1:
			failures.append("Hero did not receive the upgrade generated by NPC death")

	level.item_instances.clear()
	upgrade = null
	npc = null
	hero = null
	level = null
	Game.current_level = original_level
	_delete_config()
	return failures

func _find_item(items: Dictionary, item_id: String):
	for item in items.values():
		if str(item.item_data.get("id", "")) == item_id:
			return item
	return null

func _write_config(config: Dictionary) -> void:
	var file := FileAccess.open(TEST_CONFIG_PATH, FileAccess.WRITE)
	file.store_string(JSON.stringify(config))
	file.close()

func _delete_config() -> void:
	var absolute := ProjectSettings.globalize_path(TEST_CONFIG_PATH)
	if FileAccess.file_exists(absolute):
		DirAccess.remove_absolute(absolute)
